### ISSUE TITLE
Any plans to port it to UWP?

### ISSUE THREAD

**Issue by MihaMarkic** [0x53A/autodependencyproperty.fody#1]
Any plans to port it to UWP?

**Comment by 0x53A** [comment]
Hi @MihaMarkic , I cloned the source from https://bitbucket.org/robertvazan/autodependencyproperty.fody some time ago, but don't plan to maintain it.

You could ask the original author on bitbucked or do it yourself. =)

**Comment by MihaMarkic** [comment]
Lol, missed that since I was browsing on the phone, yes, indeed.
